### ISSUE TITLE
Add try-except block?

### ISSUE THREAD

**Issue by valosekj** [valosekj/image_shuffler#1]
https://github.com/valosekj/image_shuffler/blob/0e3a0b43c4f09e9b36bea4865e997db4f5bfc841/picture_scrambler.py#L31

Má smysl přidat do funkce kontrolující vstupní adresář try-except na odchycení OSError? Např., jako zde:

https://stackoverflow.com/questions/15259421/error-handling-for-when-a-directory-doesnt-exist

**Comment by vichi99** [comment]
Pro tvůj případ asi ne. Jelikož ty máš jedno účelový script a už kontroluje validní cesty atp pomocí - `os.path.exists`, `os.path.isdir` atp. Když není něco ok tak to vypíše `print` a nepokračuje dále. Myslím ohledně tady těch file procesů.
Pokud nastane nějaká opravdová chyba, tak uvidíš traceback a můžeš to hned opravit. Tenhle script budeš používat jen ty nebo kolegové, tj. někdo z IT. Kdyby si dával script, kód (s více soubory) někomu někam atp. tak je samozřejmě lepší použivát `try`.
`try` Má větší a bude mít větší smysl když použiješ pro scramblování obrázků přímo, tam může nastat více problému.
